import 'package:postgres/postgres.dart';
import 'package:self_hosted_server/src/repositories/pg_helpers.dart';
import 'package:shorebird_code_push_protocol/shorebird_code_push_protocol.dart';

/// Data access layer for release and patch artifacts.
class ArtifactRepository {
  const ArtifactRepository(this._pool);

  final Pool _pool;

  /// Creates a release artifact record.
  Future<int> createReleaseArtifact({
    required int releaseId,
    required String arch,
    required ReleasePlatform platform,
    required String hash,
    required int size,
    required String storagePath,
    String? podfileLockHash,
    bool canSideload = false,
  }) async {
    final result = await _pool.execute(
      Sql.named(
        '''INSERT INTO release_artifacts
             (release_id, arch, platform, hash, size, storage_path,
              podfile_lock_hash, can_sideload)
           VALUES (@releaseId, @arch, @platform, @hash, @size,
                   @storagePath, @podfileLockHash, @canSideload)
           RETURNING id''',
      ),
      parameters: {
        'releaseId': releaseId,
        'arch': arch,
        'platform': platform.name,
        'hash': hash,
        'size': size,
        'storagePath': storagePath,
        'podfileLockHash': podfileLockHash,
        'canSideload': canSideload,
      },
    );
    return result.first[0]! as int;
  }

  /// Creates a patch artifact record.
  Future<int> createPatchArtifact({
    required int patchId,
    required String arch,
    required ReleasePlatform platform,
    required String hash,
    required int size,
    required String storagePath,
    String? hashSignature,
    String? podfileLockHash,
  }) async {
    final result = await _pool.execute(
      Sql.named(
        '''INSERT INTO patch_artifacts
             (patch_id, arch, platform, hash, size, storage_path,
              hash_signature, podfile_lock_hash)
           VALUES (@patchId, @arch, @platform, @hash, @size,
                   @storagePath, @hashSignature, @podfileLockHash)
           RETURNING id''',
      ),
      parameters: {
        'patchId': patchId,
        'arch': arch,
        'platform': platform.name,
        'hash': hash,
        'size': size,
        'storagePath': storagePath,
        'hashSignature': hashSignature,
        'podfileLockHash': podfileLockHash,
      },
    );
    return result.first[0]! as int;
  }

  /// Returns all release artifacts for a release.
  Future<List<ReleaseArtifact>> getReleaseArtifacts({
    required int releaseId,
    String? arch,
    ReleasePlatform? platform,
  }) async {
    var where = 'WHERE ra.release_id = @releaseId';
    final params = <String, Object?>{'releaseId': releaseId};

    if (arch != null) {
      where += ' AND ra.arch = @arch';
      params['arch'] = arch;
    }
    if (platform != null) {
      where += ' AND ra.platform = @platform';
      params['platform'] = platform.name;
    }

    final result = await _pool.execute(
      Sql.named(
        '''SELECT ra.id, ra.release_id, ra.arch, ra.platform, ra.hash,
                  ra.size, ra.storage_path, ra.podfile_lock_hash, ra.can_sideload
           FROM release_artifacts ra
           $where''',
      ),
      parameters: params,
    );

    return result.map(_rowToReleaseArtifact).toList();
  }

  /// Returns a map of artifact id → storage_path for all release artifacts
  /// in a release.
  Future<Map<int, String>> getReleaseArtifactStoragePaths(
    int releaseId,
  ) async {
    final result = await _pool.execute(
      Sql.named(
        'SELECT id, storage_path FROM release_artifacts '
        'WHERE release_id = @releaseId',
      ),
      parameters: {'releaseId': releaseId},
    );
    return {
      for (final row in result) row[0]! as int: row[1]! as String,
    };
  }

  /// Returns the storage path for a patch artifact.
  Future<String?> getPatchArtifactStoragePath(int artifactId) async {
    final result = await _pool.execute(
      Sql.named(
        'SELECT storage_path FROM patch_artifacts WHERE id = @id',
      ),
      parameters: {'id': artifactId},
    );
    if (result.isEmpty) return null;
    return result.first[0]! as String;
  }

  ReleaseArtifact _rowToReleaseArtifact(ResultRow row) {
    final cols = row.toColumnMap();
    return ReleaseArtifact(
      id: cols['id']! as int,
      releaseId: cols['release_id']! as int,
      arch: cols['arch']! as String,
      platform: ReleasePlatform.values.byName(decodeColumn(cols['platform'])),
      hash: cols['hash']! as String,
      size: cols['size']! as int,
      url: '', // URL is generated by the storage service
      podfileLockHash: cols['podfile_lock_hash'] as String?,
      canSideload: cols['can_sideload']! as bool,
    );
  }
}
